# Generated by Django 6.0 on 2025-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_uploaded_at_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
